services:
  db_postgres:
    restart: unless-stopped
    image: postgres:15.13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD:  ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck: # нужно если требуется чтобы запуск контейнера с redis был произведен только после запуска контейнера postgres
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s   # интервал между проверками 
      timeout: 5s   # максимальное время выполнения проверки
      retries: 5     # количество попыток перед объявлением "unhealthy"
    ports:
    - 5432:5432
    volumes:
    - pg_data:/var/lib/postgresql/data

  redis:
    restart: unless-stopped
    image: redis:7
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
    - "6379:6379"
    volumes:
    - redis_data:/data
    depends_on:
      db_postgres:
        condition: service_healthy

volumes:
  pg_data:
  redis_data:

