"""update user table

Revision ID: 38c0a2b5321b
Revises: 844a8c5168c6
Create Date: 2025-08-09 14:04:07.418205

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "38c0a2b5321b"
down_revision: Union[str, Sequence[str], None] = "844a8c5168c6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("foo", sa.Integer(), nullable=False))
    op.add_column("user", sa.Column("bar", sa.Integer(), nullable=False))
    op.create_unique_constraint(
        op.f("uq_user_foo_bar"), "user", ["foo", "bar"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_user_foo_bar"), "user", type_="unique")
    op.drop_column("user", "bar")
    op.drop_column("user", "foo")
    # ### end Alembic commands ###
